development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis:https://blog.heroku.com/real_time_rails_implementing_websockets_in_rails_5_with_action_cable" } %>
  channel_prefix: Discord_production

  